version: '3.8'
networks:
  app-network:
services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:
    depends_on:
      - backend    

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    networks:
      app-network:
    volumes:
      - ./:/var/www
    #  - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - "db:database"
    #entrypoint: .docker/run.sh
    depends_on:
      - db      
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3388:3306"
    networks:
      app-network:  
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  artisan:
   build:
    context: .docker/php
    dockerfile: dockerfile
  # command: '/var/www/php artisan migrate:fresh --seed'
   networks:
    app-network: 
   volumes:
    - ./:/var/www
    - .env:/var/www/.env
   entrypoint: ["/bin/sh","-c"]
   command:
   - |
     php artisan migrate:fresh
     php artisan db:seed
   depends_on:
   - db
   - webserver
   - backend
  
volumes:
    mysql:  