FROM php:8.1-fpm


# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install Postgre PDO
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Setup working directory
WORKDIR /var/www/

# Create User and Group
# Grant Permissions
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy permission to selected user
COPY --chown=www:www . .

# RUN composer install --optimize-autoloader --no-dev; \
#     php artisan key:generate --force; \
#     php artisan migrate; \
#     php artisan db:seed; \
#     php artisan cache:clear; \
#     php artisan config:cache; \
#     php artisan route:cache; \
#     php artisan storage:link; \
#     chown -R www:www /var/www;

# Change current user to www
USER www

EXPOSE 9000

CMD ["php-fpm"]
